
// Track Data Registry
// Supports loading from Lovely Track Data (JSON) + Built-in Definitions

import { tracks as fallbackTracks } from './fallback_tracks'; // Move old static data here ideally, or keep inline

// Type definition matching Lovely Track Data v2 (partial)
export interface LovelyTrackData {
    name: string;
    trackId: string;
    length?: number;
    turns?: {
        number?: string;
        name?: string;
        marker: number; // Percentage
        direction: number; // 0 left, 1 right
    }[];
    sectors?: {
        marker: number;
    }[];
}

export interface TrackDefinition {
    id: string;
    name: string;
    path: string; // SVG Path 'd' attribute
    viewBox: string; // SVG viewBox "min-x min-y width height"
    length: number; // In meters
    corners: { id: string; name: string; x: number; y: number }[];
    style: {
        strokeColor: string;
        fillColor: string;
    }
}

// Try to load external data if available
let lovelyTracks: Record<string, LovelyTrackData> = {};
try {
    // This file is generated by the fetch script
    lovelyTracks = require('../lovely_tracks.json');
} catch (e) {
    console.warn("Lovely Track Data not found. Using built-in fallbacks.");
}

// Map Lovely data to our TrackDefinition format
// NOTE: Lovely data does NOT include SVG paths typically, just turn markers/names.
// So we still need SVG paths for the map visualizer.
// This registry primarily serves the *visualizer*.
// If Lovely data is just telemetry markers, it enriches the data but doesn't replace the SVG.

export const tracks: Record<string, TrackDefinition> = {
    ...fallbackTracks,
    // Add logic here to merge Lovely data if it contained SVGs (it usually doesn't, it's metadata)
};

// Helper to get turn names from Lovely Data if matching track found
export function getTrackMetadata(trackId: string) {
    // Normalize ID
    const key = Object.keys(lovelyTracks).find(k => k.toLowerCase().includes(trackId.toLowerCase()));
    if (key) return lovelyTracks[key];
    return null;
}
