# =====================================================================
# DigitalOcean App Platform Specification
# BlackBox Racing - AI-Powered iRacing Coach
# =====================================================================

name: blackbox-racing

# Region - choose closest to your users
region: nyc

# Environment variables shared across services
envs:
  - key: NODE_ENV
    value: production

services:
  # Backend API Server
  - name: api
    github:
      repo: SingSongScreamAlong/ProjectBlackBox
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    docker_target: server
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs  # $5/mo - upgrade as needed
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 30
    envs:
      - key: DATABASE_URL
        scope: RUN_TIME
        type: SECRET
      - key: PG_CONNECTION_STRING
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: CORS_ORIGINS
        scope: RUN_TIME
        value: ${APP_URL},${dashboard.PUBLIC_URL}
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ELEVENLABS_API_KEY
        scope: RUN_TIME
        type: SECRET

  # Frontend Dashboard
  - name: dashboard
    github:
      repo: SingSongScreamAlong/ProjectBlackBox
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    docker_target: dashboard
    http_port: 80
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: REACT_APP_API_URL
        scope: BUILD_TIME
        value: ${api.PUBLIC_URL}
      - key: REACT_APP_WS_URL
        scope: BUILD_TIME
        value: ${api.PUBLIC_URL}

# Managed Database
databases:
  - name: blackbox-db
    engine: PG
    version: "15"
    size: db-s-dev-database  # $7/mo - smallest
    num_nodes: 1
